cassandra:
    build: ../cassandra/.
mimic:
    build: ../mimic/.
poppy:
    build: ../../.
    ports:
        - "8888:8081"
    volumes:
        - ../../:/home/poppy
        - /etc/localtime:/etc/localtime:ro
    command:
        - /root/start_poppy.sh
    links:
        - cassandra
        - mimic
